CUDA_VISIBLE_DEVICES=0 deepspeed --master_port 5200 train.py \
      --train_path data/spo_0.json \
      --model_name_or_path /home/shenfei/models/chatglm3-6b \
      --per_device_train_batch_size 1 \
      --max_len 768 \
      --max_src_len 512 \
      --learning_rate 1e-4 \
      --weight_decay 0.1 \
      --num_train_epochs 2 \
      --gradient_accumulation_steps 4 \
      --warmup_ratio 0.1 \
      --mode glm \
      --train_type ptuning \
      --seed 1234 \
      --ds_file ds_zero2_no_offload.json \
      --gradient_checkpointing \
      --show_loss_step 10 \
      --pre_seq_len 16 \
      --prefix_projection True \
      --output_dir ./output-glm